#!/bin/bash
cwd=$(pwd)
cd Keras-examples/ && \
	git init && \
	git remote add origin -f https://github.com/fchollet/keras && \
	git config core.sparsecheckout true && \
	echo "examples/*" >> .git/info/sparse-checkout && \
	git pull --depth=2 origin master
cd $cwd

mkdir -p tensorflow
cd tensorflow
git init && \
	git remote add origin -f https://github.com/emsi/tensorflow && \
	git config core.sparsecheckout true && \
	echo "tensorflow/tools/docker/*" >> .git/info/sparse-checkout && \
	echo "tensorflow/tools/ci_build/*" >> .git/info/sparse-checkout && \
	git pull --depth=2 origin master
cd $cwd

nvidia-docker build -f Dockerfile-py3       --rm=true -t emsi/deep-learning:gpu-py3-TF-1.10 .
