#!/bin/bash
cwd=$(pwd)
cd Keras-examples/ && \
git init && \
git remote add origin -f https://github.com/fchollet/keras && \
git config core.sparsecheckout true && \
echo "examples/*" >> .git/info/sparse-checkout && \
git pull --depth=2 origin master
cd $cwd
#nvidia-docker build --rm=true -t emsi/deep-learning .
#nvidia-docker build -f Dockerfile-py3 --rm=true -t emsi/deep-learning:gpu-py3 .
#nvidia-docker build -f Dockerfile-py3-TF-1.2 --no-cache --rm=true -t emsi/deep-learning:gpu-py3-TF-1.2 .
#nvidia-docker build -f Dockerfile-py3-TF-1.2-conda --rm=true -t emsi/deep-learning:gpu-py3-TF-1.2-conda .
nvidia-docker build -f Dockerfile-py3-TF-1.3       --rm=true -t emsi/deep-learning:gpu-py3-TF-1.3 .
#nvidia-docker build -f Dockerfile-py3-TF-1.3-conda --rm=true -t emsi/deep-learning:gpu-py3-TF-1.3-conda .
