FROM tensorflow/tensorflow:1.12.0-gpu-py3 

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	wget \
	vim \
	inetutils-ping \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install miniconda
RUN wget --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
	bash ./Miniconda3-latest-Linux-x86_64.sh -b -p /anaconda3 && \
	rm -f ./Miniconda3-latest-Linux-x86_64.sh

ENV PATH /anaconda3/bin:$PATH
RUN conda upgrade conda && \
	conda upgrade --all && \
	conda upgrade conda  && \
	conda install nb_conda jupyter notebook

# numpy jupyter notebook
# Create py3 TF environment s
RUN conda install -c numpy matplotlib scikit-learn nltk openpyxl seaborn pandas gensim Keras h5py Keras regex tensorflow-gpu jupyter tensorboard
RUN conda install -c pytorch pytorch-nightly cuda92
RUN conda install -c fastai torchvision-nightly
RUN conda install -c fastai fastai


# Install Pycharm
RUN apt-get update && apt-get install --no-install-recommends -y \
  python3 python3-dev python3-setuptools python3-pip \
  gcc git openssh-client vim \
  libxtst-dev libxext-dev libxrender-dev libfreetype6-dev \
  libfontconfig1 \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /opt/pycharm
WORKDIR /opt/pycharm

ARG pycharm_source=https://download-cf.jetbrains.com/python/pycharm-professional-2018.3.tar.gz
ADD $pycharm_source /opt/pycharm/installer.tgz

RUN tar --strip-components=1 -xzf installer.tgz && rm installer.tgz

RUN /usr/bin/python3 /opt/pycharm/helpers/pydev/setup_cython.py build_ext --inplace

RUN useradd -ms /bin/bash developer
USER developer
ENV HOME /home/developer

ARG pycharm_pro_local_dir=.PyCharm2018.3
RUN mkdir /root/.PyCharm \
  && ln -sf /root/.PyCharm /root/$pycharm_pro_local_dir

# Set shell to bash
ENV SHELL /bin/bash

# Set locale
ENV LANG "C.UTF-8"
ENV LC_COLLATE "C.UTF-8"

CMD [ "/opt/pycharm/bin/pycharm.sh" ]
