FROM gcr.io/tensorflow/tensorflow:1.2.0-gpu-py3 

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip --no-cache-dir install scikit-learn nltk openpyxl seaborn pandas gensim imbalanced-learn Keras h5py Keras many_stop_words regex folium bokeh branca xlrd fiona

RUN mkdir -p /notebooks/TF-examples && \
	mv /notebooks/*.ipynb /notebooks/TF-examples 
RUN mkdir -p /notebooks/Keras-examples
COPY Keras-examples/examples /notebooks/Keras-examples


#WORKDIR /notebooks
#CMD ["/run_jupyter.sh"]
