services:
  dl:
    runtime: nvidia
    image: emsi/deep-learning:py${PY_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 22
    ports:
    # jupyter
      - "8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HOME=${HOME}
    user: ${COMPOSE_USER_ID}:${COMPOSE_GROUP_ID}
    working_dir: ${HOME}

    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - sudoers:/etc/sudoers.d/:ro
      - /etc/localtime:/etc/localtime:ro
      - home:/home/
      - ${HOME}/git:${HOME}/git
      - ${HOME}/.ssh/authorized_keys:${HOME}/.ssh/authorized_keys:ro
      - ${HOME}/.cache/huggingface/:${HOME}/.cache/huggingface/
    init: true
    restart: always
    depends_on:
      - sudo

  sudo:
    image: emsi/deep-learning:py${PY_VERSION}
    volumes:
      - ./sudoers.sh:/sudoers.sh
      - sudoers:/etc/sudoers.d/:rw
      - home:/home/

    command: /sudoers.sh

volumes:
  sudoers:
  home:
