ARG TF_VERSION
FROM tensorflow/tensorflow:$TF_VERSION

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	wget \
	vim \
	inetutils-ping \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 --no-cache-dir install scikit-learn nltk openpyxl seaborn pandas gensim imbalanced-learn h5py many_stop_words regex folium bokeh branca xlrd fiona tqdm autopep8 pydot tables statsmodels Pillow torch torchvision jupyterlab black isort jupyter_contrib_nbextensions jupyter_nbextensions_configurator

# Installing nodejs with npm
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash && \
	apt-get install -y nodejs && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

#RUN apt-get update && apt-get install -y npm && \
#     apt-get clean && \
#    rm -rf /var/lib/apt/lists/*

RUN jupyter contrib nbextension install --user --skip-running-check && jupyter nbextensions_configurator enable --user 

#RUN jupyter labextension install @krassowski/jupyterlab_go_to_definition @ryantam626/jupyterlab_code_formatter && \
#	 pip install jupyterlab_code_formatter && jupyter serverextension enable --py jupyterlab_code_formatter


RUN mkdir -p /notebooks/
COPY nbconfig /notebooks/.jupyter/
ENV HOME /notebooks
WORKDIR /notebooks

# Set shell to bash
ENV SHELL /bin/bash

# Set locale
ENV LANG "C.UTF-8"
ENV LC_COLLATE "C.UTF-8"


#CMD ["/run_jupyter.sh"]
