version: '2.4'

services:
  deep-learning:
    runtime: nvidia
    image: emsi/deep-learning:${TF_VERSION}
    container_name: dl-${TF_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "8888"
    ports:
    # jupyter
      - "8888:8888"
    entrypoint: jupyter-lab --ip=0.0.0.0 --allow-root
    volumes:
            - ${HOME}:/notebooks/
  deep-learning-devel:
    image: emsi/deep-learning-devel:${TF_VERSION}
    container_name: dl-devel-${TF_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile-devel
    expose:
      - "22"
      - "8888"
    # ssh
    ports:
      - "22:3322"
        #    - target: 22
        #      published: 3322
        #      protocol: tcp
        #      mode: host
    volumes:
      - ${HOME}:${HOME}
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
