version: '2.4'

services:
  dl:
    runtime: nvidia
    image: emsi/deep-learning:${TF_VERSION}-py${PY_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 22
    ports:
    # jupyter
      - "8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HOME=${HOME}
    user: ${COMPOSE_USER_ID}:${COMPOSE_GROUP_ID}
    working_dir: ${HOME}
    command: jupyter-lab --ip=0.0.0.0
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - sudoers:/etc/sudoers.d/:ro
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}:${HOME}
    init: true
    restart: always
    depends_on:
      - sudo

  sudo:
    image: emsi/deep-learning:${TF_VERSION}-py${PY_VERSION}
    volumes:
      - ./sudoers.sh:/sudoers.sh
      - sudoers:/etc/sudoers.d/:rw

    command: /sudoers.sh

volumes:
  sudoers:
