ARG TF_VERSION
ARG PY_VERSION
FROM emsi/deep-learning:${TF_VERSION}-py${PY_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-server \
        sudo \
	net-tools \
	iproute2 \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# For development we use remote ssh
RUN sed -i -e 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' \
	-e 's/UsePAM yes/UsePAM no/' \
	/etc/ssh/sshd_config && \
	mkdir /root/.ssh && chmod 700 /root/.ssh && mkdir /var/run/sshd && \
	curl https://github.com/emsi.keys | tee -a /root/.ssh/authorized_keys && \
	/bin/true > /etc/bash.bashrc

EXPOSE 22
RUN echo "export LANG=C.UTF-8" >> /etc/profile &&\
    echo "export LC_COLLATE=C.UTF-8" >> /etc/profile && \
    true
CMD ["/usr/sbin/sshd", "-D", "-e"]
