version: '2.4'

services:
  dl:
    runtime: nvidia
    image: emsi/deep-learning:${TF_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "8888"
    ports:
    # jupyter
      - "8888"
    environment:
      - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}_dl
      - VIRTUAL_PORT=8888
    entrypoint: jupyter-lab --ip=0.0.0.0 --allow-root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}:/notebooks/
  dl-devel:
    image: emsi/deep-learning-devel:${TF_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile-devel
    expose:
      - "22"
      - "8888"
    # ssh
    ports:
      - "3322:22"
        #    - target: 22
        #      published: 3322
        #      protocol: tcp
        #      mode: host
    volumes:
      - ${HOME}:${HOME}
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
